### ISSUE TITLE
initialValues issue

### ISSUE THREAD

**Issue by sgriffin916** [selbekk/calidation#10] opened 2018-06-15 16:28 UTC
When I use the initialValues object, it does not let me delete all of the characters in the text box.  When I do, it just goes back to the original value.   For instance, if the first name is "Stephen", it lets me remove the characters and change it to "S" but once I delete the final character, it changes it back to "Stephen".

This does not happen when I use the setField to put the values into the textbox.

Is this the expected behavior?  I am trying to figure out how to load a form when editing a user but still allow non-required fields to be clearable.  I would use setField to set the form elements original values but I am not sure how get access to this function when the component mounts.

**Comment by selbekk** [comment] 2018-06-21 12:36
Hi @sgriffin916 - thanks for opening this issue! It's a know issue, and I'm thinking of ways to fix it.

It's a surprisingly tricky thing to fix, because of the internal structure of this lib, but I'm looking into solutions.

For now, a great workaround is using the input's `defaultValue` prop.

**Comment by selbekk** [comment] 2018-06-21 12:37
As this is a duplicate of #6, I'm closing this one in favor of #6.

**Closed by selbekk** 2018-06-21 12:37 UTC
Labels: bug
