### ISSUE TITLE
Check the render method of withValidators(Form).

### ISSUE THREAD

**Issue by edgarchiroleo** [selbekk/calidation#2] opened 2018-04-27 13:45 UTC
Hi, I'm trying to test calidation within a component, this is the code

```js
import React from "react";
import { Form } from "calidation";

class Entity extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      edit: false
    };
    this.saveData = this.saveData.bind(this);
  }

  saveData() {}
  render() {
    return (
      <Form onSubmit={this.saveData}>
        <div className="row">
          <div className="col-md-12" />
        </div>
      </Form>
    );
  }
}

```

I find this error. What could be wrong doing

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `withValidators(Form)`.

**Comment by selbekk** [comment] 2018-04-27 14:39
Hi there! Thanks for trying this out.

I've tried to reproduce your error, but this seems to be working fine with me: https://codesandbox.io/s/ojl9096q45

Can you please try to create a reproducible example?

**Comment by selbekk** [comment] 2018-05-14 11:37
I'm closing this for now. Please let me know if you're still struggling 👍

**Closed by selbekk** 2018-05-14 11:37 UTC
